version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.75"

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
