name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment
        run: |
          python -m venv venv

      - name: "Test Rust"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo test

      - name: Install and test (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          source venv/Scripts/activate
          python -m pip install --upgrade pip
          pip install -U pip maturin
          pip install -r requirements/test.txt
          maturin develop --release
          pytest tests/

      - name: Install and test
        if: ${{ matrix.os != 'windows-latest' && !((matrix.python-version == '3.12') && (matrix.os == 'ubuntu-latest')) }}
        shell: bash
        run: |
          source venv/bin/activate
          pip install -U pip maturin
          pip install -r requirements/test.txt
          maturin develop --release
          pytest tests/

      - name: Install and test (incl coverage)
        if: ${{ (matrix.python-version == '3.12') && (matrix.os == 'ubuntu-latest') }}
        shell: bash
        run: |
          source venv/bin/activate
          pip install -U pip maturin
          pip install -r requirements/test.txt
          maturin develop --release
          pytest tests/ --cov=whenever

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          pip install -U pip maturin twine
          pip install -r requirements/lint.txt
          make ci-lint

  Typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install -U pip maturin
          pip install -r requirements/typecheck.txt
          pip install -r requirements/test.txt
          maturin develop
          make typecheck
